### ISSUE TITLE
Explore different data lengths

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/EEG-GAN#13]
I encountered an issue where inputting data into EEG-GAN training would crash unless the time-series were exactly 100 datapoints. 

![Screenshot_2023-05-02 13_35_52](https://user-images.githubusercontent.com/26373111/236511401-d3e64612-b1db-4040-959f-4e55d0c8f781.png)

**Comment by whyhardt** [comment]
Did you want to give a sequence of 82 data points to the GAN when it was constructed for and trained with sequences of length 100 ? In that case, this error would make sense

**Comment by whyhardt** [comment]
As far as I can remember, that error did not show up when training on other datasets - or were they sampled down to 100 data points as well?

**Comment by chadcwilliams** [comment]
This issue was created a long time ago, so it could just be I screwed up (as I wasn't familiar with the code back then). I kept it up here just to test it and make sure it's not a problem anymore.

**Comment by whyhardt** [comment]
aaaah okay I understand

**Comment by chadcwilliams** [comment]
This is no longer an issue.
