### ISSUE TITLE
Argument cleanup

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/EEG-GAN#15]
Once the code is in a state we all like, I would like to do a detailed review of the input parameter names. Some things I've felt need fixing:

Filename argument: Filename argument is 'path_dataset' in gan_training_main.py but 'file' in everything else. Let's make it consistent.

Filename path: I need to test this explicitly to know exactly which is which, but I believe 'path_dataset' requires the data folder in the filename 'path_dataset=data/gansMultiCondition.csv' while others such as generate_samples_main.py automatically adds the path. Maybe we can make it so they will all automatically add the path if there is no '/' in the argument ('/' indicating a path), but open to anything as long as they are consistent. 

channel_label: This was my change, but I think we should change it to channel to match the briefness of the condition argument.

I think a detailed look at the help would be useful too and potentially removing some arguments that are not currently stable. Finally, updating the docs with examples of how to use every argument would be useful too.

**Comment by whyhardt** [comment]
All:
kw_timestep; kw_timestep_dataset -> kw_time
conditions -> kw_conditions
channel_label -> kw_channel
path_dataset -> data
removed load_checkpoint
path_checkpoint -> checkpoint (shortcut to get to checkpoint.pt: you can type in any ascii character; if not found loading checkpoint.pt)

GAN:
removed learning_rate (keeping generator_lr and discriminator_lr)
path_autoencoder -> autoencoder
removed ddp_backend

AE:
timeseries_out -> time_out
removed ddp_backend

generate_samples:
path_file -> path_model
