### ISSUE TITLE
Update all dependencies

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/EEG-GAN#26]
EEG-GAN currently states that it requires torch 1.12.1, but this is not true. It works with all versions after that too. So, we should change dependencies on the next release to signify this.

**Comment by whyhardt** [comment]
You can create a requirements.txt file with all updated dependencies automatically

**Comment by chadcwilliams** [comment]
Updated this issue to include a redo of dependencies.

**Comment by TheLemonPig** [comment]
The only dependency that needs to be added from what I have tried so far is ```tqdm```

**Comment by chadcwilliams** [comment]
For reference, this is what Joshua used as dependencies:

```
pip3 install torch torchvision torchaudio torchsummary 
pip install pandas==1.3.4
pip install numpy==1.21.4
pip install matplotlib==3.5.0
pip install scipy==1.8.0
pip install einops==0.4.1
pip install scikit-learn==1.1.2
```

Let's also make sure to change these so that they do not require such specific versions

**Comment by chadcwilliams** [comment]
Completed with #104
