### ISSUE TITLE
Ordering of data

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/EEG-GAN#38]
@whyhardt does the dataloader still order the data of the timeseries header? It looks like this has been removed but I wanted to confirm. 

If it still does, I'd like to open a discussion about whether it should. I think people will always have the data ordered correctly (we can make this a requirement) and that this is more likely to cause issues than help people. If it does not - I'll close the issue

**Comment by whyhardt** [comment]
@chadcwilliams I'm not fully aware of the code and I don't have access to my computer right now. But as far as I remember, it shouldn't sort the data since the loader is looking for a substring in the header (e.g. time) and ignores the rest.
