### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/checkpoint_01.pt'"

### ISSUE THREAD

**Issue by thelegitdolt** [AutoResearch/EEG-GAN#40]
Hey! I've been trying to use EEGGAN for a project, and am currently running into an issue. I've trained the dataset on one of the cvs files you had, but am currently running into an issue and getting ` No such file or directory: 'trained_models/checkpoint_01.pt'` whenever I try to run. 

what could this be caused by? 
My code: https://gist.github.com/thelegitdolt/750d8c75bfe4b5525037b5494aed8848
The exact error: https://gist.github.com/thelegitdolt/9655b08b05c7e74b532a3087c8cfac57

Thank you!

**Comment by thelegitdolt** [comment]
hey i managed to figure this out, no need for anything else, sorry for the inconvenience!!!

**Comment by chadcwilliams** [comment]
Hello, thank you for your interest in the package! I am glad you figured it out and we'll look into this issue so others don't encounter it too.
