### ISSUE TITLE
AE-GAN Should force activation based on AE

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/EEG-GAN#54]
If the user accidentally uses a different activation for AE-GAN than they did for the AE, we should force change the parameter to what was used in the AE. Or else, we could remove the parameter for AE-GAN and just use the activation from AE (but not for GAN alone).

**Comment by whyhardt** [comment]
That's a good point in the case of AE-GAN! If the user wants to use TransformerGAN for some reason (which is not tested yet - but we could do that at some point) the activation function should still be there. But as you said, in the case of AE-GAN there's no actual benefit and even quite a conflict potential in keeping the activation function flexible.

**Comment by whyhardt** [comment]
added functionality; but only relevant for AE-FF-GAN; AE-TTS-GAN does not take custom activation function
