### ISSUE TITLE
GAN Training script does not close everything properly

### ISSUE THREAD

**Issue by whyhardt** [AutoResearch/EEG-GAN#62]
Running gan training several times in a row seems to deplete some resources
Exact steps were:
1. Running DDP Training on Oscar for a few epochs
2. KeyboardInterrupt
3. Re-running training
4. Estimated time became twice as high

**Comment by whyhardt** [comment]
Could not reproduce on single GPU (non-DDP training)
Added cuda-delete-cache in the beginning of each GAN-training as workaround.

**Comment by chadcwilliams** [comment]
In my most recent trainings, I also didn't see this issue emerge. I will try to reproduce it explicitly with GPUs on Oscar and on Google Colab. If I can't reproduce it, I'll close the issue.

**Comment by chadcwilliams** [comment]
Seems fixed now (could not reproduce the issue).
