### ISSUE TITLE
GAN-Training: type=tr does not work

### ISSUE THREAD

**Issue by whyhardt** [AutoResearch/EEG-GAN#82]
I get an error with the most current pytorch=2.2.2
Does it work with older versions? Cannot downgrade to <2.0 because torchaudio and torchvision are not supported.

Error: 
RuntimeError: derivative for aten::_scaled_dot_product_efficient_attention_backward is not implemented

Just kick out type=tr and leave only ff and tts?

**Comment by chadcwilliams** [comment]
Yes, I agree with that. In fact, as part of our code cleanup I was going to ask whether we need any except for TTS. I have only tested TTS and none of the others, so if we still agree that we want to scrape the code down to the bare minimum, then I think we can take all but TTS out for v2.0. 

We can keep them on an exploratory branch if we plan on working with them in the future.

**Comment by chadcwilliams** [comment]
I am closing this and leaving it as a task for issue #16
