### ISSUE TITLE
visualize_main has fallen behind on updates

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/EEG-GAN#96]
I haven't been updating this script, whoops! Joshua found one bug where it is looking for kw_timeseries rather than kw_time, which is easily fixable.

It is also lacking some stuff it could have, including functionality for the autoencoder. I have some ideas on how we can improve it based on the work I have been doing and understanding what is important to me to visualize.

**Comment by whyhardt** [comment]
updated! Also added test-suite for easier validation.
