### ISSUE TITLE
Generating samples main crashes if GAN didn't have electrode label

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/EEG-GAN#97]
Joshua noticed a bug where if you don't give an electrode label to the GAN, the generate_samples script still expects one. 

Below you will see on line 256 it includes kw_channel in the created list but this is empty so the length is smaller than the data (or maybe it's the other way around).

![Screenshot_2024-04-26 17_43_26](https://github.com/AutoResearch/EEG-GAN/assets/26373111/836399ae-1daa-46c6-9763-6ac56ad84556)

**Comment by whyhardt** [comment]
Solved. The problem was not that it expected an electrode but that the conditions-field has changed in the case for no conditions from being an empty list `conditions = []` to `conditions = ['']`. Therefore, it added the condition `''` and had one field too much.
